# Generated by Smithery (manually refined)
# Use a Node.js image with build tools
FROM node:24-slim AS build

WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the source code
COPY . .

# Build the project
RUN npm run build

# Final runtime image
FROM node:24-slim AS release

WORKDIR /app

# Copy the built files and production dependencies
COPY --from=build /app/dist ./dist
COPY --from=build /app/package*.json ./

# Install production dependencies only
RUN npm install --omit=dev

# Start the MCP server
ENTRYPOINT ["node", "dist/src/index.js"]
